version: '3.7'

services:
  docs:
    image: letfn/drone-hugo
    volumes:
      - ".:/app/src"
    environment:
      - PLUGIN_WATCH=yes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.whoa.bot`)"
      - "traefik.http.services.docs.loadbalancer.server.port=1313"

networks:
  default:
    external:
      name: kitt
